const mongoose = require("mongoose");
const { Schema } = mongoose;

const songSchema = new Schema({
  songName: { type: String, required: true,index: true },
  artist: { type: String, required: true },
  album: { type: String },
  duration: { type: String },
  releaseDate: { type: Date },
  genre: 
    {
      type: String,
      index: true,
      enum: [
        "Pop",
        "K-Pop",
        "J-Pop",
        "Synthpop",
        "Electropop",
        "Pop Rock",
        "Indie Pop",
        "Bubblegum Pop",
        "Rock",
        "Classic Rock",
        "Hard Rock",
        "Soft Rock",
        "Alternative Rock",
        "Indie Rock",
        "Progressive Rock",
        "Punk Rock",
        "Grunge",
        "Post-Rock",
        "Folk Rock",
        "Hip-Hop",
        "Rap",
        "Trap",
        "Drill",
        "Conscious Rap",
        "Gangsta Rap",
        "Alternative Hip-Hop",
        "Mumble Rap",
        "Electronic",
        "House",
        "Techno",
        "Trance",
        "Dubstep",
        "Drum and Bass",
        "EDM",
        "Ambient",
        "Synthwave",
        "Future Bass",
        "R&B",
        "Soul",
        "Neo-Soul",
        "Contemporary R&B",
        "Funk",
        "Jazz",
        "Smooth Jazz",
        "Bebop",
        "Fusion",
        "Latin Jazz",
        "Acid Jazz",
        "Classical",
        "Baroque",
        "Romantic",
        "Opera",
        "Symphony",
        "Country",
        "Bluegrass",
        "Outlaw Country",
        "Country Pop",
        "Americana",
        "Blues",
        "Delta Blues",
        "Chicago Blues",
        "Texas Blues",
        "Reggae",
        "Dancehall",
        "Dub",
        "Ska",
        "Metal",
        "Heavy Metal",
        "Thrash Metal",
        "Death Metal",
        "Black Metal",
        "Doom Metal",
        "Power Metal",
        "Folk",
        "Indie Folk",
        "Celtic Folk",
        "World Music",
        "Afrobeat",
        "Bossa Nova",
        "Flamenco",
        "Soca",
        "Experimental",
        "Noise",
        "Drone",
        "Gospel",
        "Disco",
        "New Wave",
        "Industrial",
      ],
    },
  imageUrl: { type: String },
  previewLyrics: { type: String, required: true }, // New field for song lyrics
  audio_url: [{ type: Schema.Types.ObjectId, ref: "Audio" }],
});

const Song = mongoose.model("Song", songSchema);
module.exports = Song;
