const mongoose = require("mongoose");
const { Schema } = mongoose;

const userSchema = new Schema(
  {
    firstName: {
      type: String,
      required: true,
      trim: true,
      validate: {
        validator: function (v) {
          return /[A-Z][a-z]/.test(v);
        },
        message: (props) => `${props.value} is not a valid firstName!`,
      },
    },
    lastName: {
      type: String,
      required: false,
    },
    email: {
      type: String,
      required: true,
      unique: true,
      index: true,
      validate: {
        validator: function (v) {
          return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
        },
        message: (props) => `${props.value} is not a valid email!`,
      },
    },
    image: {
      type: String,
      required: false,
    },
    password: {
      type: String,
      required: true,
      min: [6, "Password should be minimum Six characters"],
    },
    gender: {
      type: String,
      required: true,
      enum: ["Male", "Female", "Other"],
    },
    age: {
      type: Number,
      required: true,
      min: [5, "Age should be minimum Eighteen"],
    },
    country: {
      type: String,
      required: true,
    },
    preferences: {
      type: [String],
      required: true,
      enum: [
        "Pop",
        "K-Pop",
        "J-Pop",
        "Synthpop",
        "Electropop",
        "Pop Rock",
        "Indie Pop",
        "Bubblegum Pop",
        "Rock",
        "Classic Rock",
        "Hard Rock",
        "Soft Rock",
        "Alternative Rock",
        "Indie Rock",
        "Progressive Rock",
        "Punk Rock",
        "Grunge",
        "Post-Rock",
        "Folk Rock",
        "Hip-Hop",
        "Rap",
        "Trap",
        "Drill",
        "Conscious Rap",
        "Gangsta Rap",
        "Alternative Hip-Hop",
        "Mumble Rap",
        "Electronic",
        "House",
        "Techno",
        "Trance",
        "Dubstep",
        "Drum and Bass",
        "EDM",
        "Ambient",
        "Synthwave",
        "Future Bass",
        "R&B",
        "Soul",
        "Neo-Soul",
        "Contemporary R&B",
        "Funk",
        "Jazz",
        "Smooth Jazz",
        "Bebop",
        "Fusion",
        "Latin Jazz",
        "Acid Jazz",
        "Classical",
        "Baroque",
        "Romantic",
        "Opera",
        "Symphony",
        "Country",
        "Bluegrass",
        "Outlaw Country",
        "Country Pop",
        "Americana",
        "Blues",
        "Delta Blues",
        "Chicago Blues",
        "Texas Blues",
        "Reggae",
        "Dancehall",
        "Dub",
        "Ska",
        "Metal",
        "Heavy Metal",
        "Thrash Metal",
        "Death Metal",
        "Black Metal",
        "Doom Metal",
        "Power Metal",
        "Folk",
        "Indie Folk",
        "Celtic Folk",
        "World Music",
        "Afrobeat",
        "Bossa Nova",
        "Flamenco",
        "Soca",
        "Experimental",
        "Noise",
        "Drone",
        "Gospel",
        "Disco",
        "New Wave",
        "Industrial",
      ],
    },
    resetPasswordToken: String,
    resetPasswordExpiresAt: Date,
    verificationToken: String,
    verificationTokenExpiresAt: Date,
  },
  { timestamps: true }
);

const User = mongoose.model("User", userSchema);
module.exports = User;
