const musicGenres = [
    { name: "Pop" },
    { name: "K-Pop" },
    { name: "J-Pop" },
    { name: "Synthpop" },
    { name: "Electropop" },
    { name: "Pop Rock" },
    { name: "Indie Pop" },
    { name: "Bubblegum Pop" },
    { name: "Rock" },
    { name: "Classic Rock" },
    { name: "Hard Rock" },
    { name: "Soft Rock" },
    { name: "Alternative Rock" },
    { name: "Indie Rock" },
    { name: "Progressive Rock" },
    { name: "Punk Rock" },
    { name: "Grunge" },
    { name: "Post-Rock" },
    { name: "Folk Rock" },
    { name: "Hip-Hop" },
    { name: "Rap" },
    { name: "Trap" },
    { name: "Drill" },
    { name: "Conscious Rap" },
    { name: "Gangsta Rap" },
    { name: "Alternative Hip-Hop" },
    { name: "Mumble Rap" },
    { name: "Electronic" },
    { name: "House" },
    { name: "Techno" },
    { name: "Trance" },
    { name: "Dubstep" },
    { name: "Drum and Bass" },
    { name: "EDM" },
    { name: "Ambient" },
    { name: "Synthwave" },
    { name: "Future Bass" },
    { name: "R&B" },
    { name: "Soul" },
    { name: "Neo-Soul" },
    { name: "Contemporary R&B" },
    { name: "Funk" },
    { name: "Jazz" },
    { name: "Smooth Jazz" },
    { name: "Bebop" },
    { name: "Fusion" },
    { name: "Latin Jazz" },
    { name: "Acid Jazz" },
    { name: "Classical" },
    { name: "Baroque" },
    { name: "Romantic" },
    { name: "Opera" },
    { name: "Symphony" },
    { name: "Country" },
    { name: "Bluegrass" },
    { name: "Outlaw Country" },
    { name: "Country Pop" },
    { name: "Americana" },
    { name: "Blues" },
    { name: "Delta Blues" },
    { name: "Chicago Blues" },
    { name: "Texas Blues" },
    { name: "Reggae" },
    { name: "Dancehall" },
    { name: "Dub" },
    { name: "Ska" },
    { name: "Metal" },
    { name: "Heavy Metal" },
    { name: "Thrash Metal" },
    { name: "Death Metal" },
    { name: "Black Metal" },
    { name: "Doom Metal" },
    { name: "Power Metal" },
    { name: "Folk" },
    { name: "Indie Folk" },
    { name: "Celtic Folk" },
    { name: "World Music" },
    { name: "Afrobeat" },
    { name: "Bossa Nova" },
    { name: "Flamenco" },
    { name: "Soca" },
    { name: "Experimental" },
    { name: "Noise" },
    { name: "Drone" },
    { name: "Gospel" },
    { name: "Disco" },
    { name: "New Wave" },
    { name: "Industrial" },
];

export const useGenres = () => {
    return musicGenres.map((genre) => {
        return genre
    })
}